name: Tests

on:
  push:

jobs:
  nix-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#blankdb -L
